test-resources:
  containers:
    mongodb:
      image-name: mongo:4.2.8
      env:
        - MONGO_INITDB_DATABASE: songdb
      command:
        - --replSet
        - rs0
      hostnames:
        - mongo.host
      exposed-ports:
        - mongo.port: 27017
      copy-to-container:
        - src/main/resources/mongo-init.js: /docker-entrypoint-initdb.d/mongo-init.js
        - src/main/resources/mongo-init.sh: /docker-entrypoint-initdb.d/mongo-init.sh